"""normalized research schema

Revision ID: 0002_research_schema
Revises: 0001_foundation
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision = "0002_research_schema"
down_revision = "0001_foundation"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_versions",
        sa.Column("model_identifier", sa.String(length=180), nullable=False),
        sa.Column("version", sa.String(length=120), nullable=False),
        sa.Column(
            "modality",
            sa.Enum(
                "text",
                "audio",
                "visual",
                "multimodal",
                name="model_modality",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("artifact_sha256", sa.String(length=64), nullable=True),
        sa.Column("license", sa.String(length=120), nullable=True),
        sa.Column("model_card_reference", sa.String(length=500), nullable=True),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_versions")),
        sa.UniqueConstraint("id", "modality", name=op.f("uq_model_versions_id_modality")),
        sa.UniqueConstraint(
            "model_identifier",
            "version",
            "modality",
            name=op.f("uq_model_versions_model_identifier_version_modality"),
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "permissions",
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        sa.UniqueConstraint("code", name=op.f("uq_permissions_code")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "roles",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("code", name=op.f("uq_roles_code")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_development_account", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.Column(
            "deleted_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("actor_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("resource_type", sa.String(length=60), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum(
                "success",
                "denied",
                "failure",
                name="audit_outcome",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("request_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_audit_logs_request_id"), "audit_logs", ["request_id"], unique=False)
    op.create_index("ix_audits_actor_time", "audit_logs", ["actor_id", "created_at"], unique=False)
    op.create_index(
        "ix_audits_resource_time",
        "audit_logs",
        ["resource_type", "resource_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("recipient_id", sa.String(length=36), nullable=False),
        sa.Column("deduplication_key", sa.String(length=120), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "in_app",
                "email",
                name="notification_channel",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("template_code", sa.String(length=80), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "sent",
                "failed",
                "cancelled",
                name="notification_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column(
            "scheduled_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "sent_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.Column(
            "deleted_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_notifications_notification_attempts")
        ),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["users.id"],
            name=op.f("fk_notifications_recipient_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint("deduplication_key", name=op.f("uq_notifications_deduplication_key")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_notifications_deleted_at"), "notifications", ["deleted_at"], unique=False
    )
    op.create_index(
        "ix_notifications_dispatch", "notifications", ["status", "scheduled_at"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_recipient_id"), "notifications", ["recipient_id"], unique=False
    )
    op.create_table(
        "reviewer_profiles",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("professional_title", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.Column(
            "deleted_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_reviewer_profiles_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_reviewer_profiles")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_reviewer_profiles_deleted_at"), "reviewer_profiles", ["deleted_at"], unique=False
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.String(length=36), nullable=False),
        sa.Column("permission_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_role_permissions_permission_id_permissions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_permissions_role_id_roles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name=op.f("pk_role_permissions")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_role_permissions_permission_id"),
        "role_permissions",
        ["permission_id"],
        unique=False,
    )
    op.create_table(
        "student_profiles",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("research_pseudonym", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.Column(
            "deleted_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_student_profiles_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_student_profiles")),
        sa.UniqueConstraint(
            "research_pseudonym", name=op.f("uq_student_profiles_research_pseudonym")
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_student_profiles_deleted_at"), "student_profiles", ["deleted_at"], unique=False
    )
    op.create_table(
        "system_settings",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_system_settings_updated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_system_settings")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role_id", sa.String(length=36), nullable=False),
        sa.Column(
            "granted_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_roles")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_user_roles_role_id"), "user_roles", ["role_id"], unique=False)
    op.create_table(
        "consent_records",
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("policy_version", sa.String(length=80), nullable=False),
        sa.Column("text_processing", sa.Boolean(), nullable=False),
        sa.Column("audio_processing", sa.Boolean(), nullable=False),
        sa.Column("visual_processing", sa.Boolean(), nullable=False),
        sa.Column("longitudinal_tracking", sa.Boolean(), nullable=False),
        sa.Column("research_data_use", sa.Boolean(), nullable=False),
        sa.Column("retain_audio", sa.Boolean(), nullable=False),
        sa.Column("retain_visual", sa.Boolean(), nullable=False),
        sa.Column("reviewer_access", sa.Boolean(), nullable=False),
        sa.Column(
            "withdrawn_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"),
            nullable=True,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.CheckConstraint(
            "NOT retain_audio OR audio_processing",
            name=op.f("ck_consent_records_audio_retention_consent"),
        ),
        sa.CheckConstraint(
            "NOT retain_visual OR visual_processing",
            name=op.f("ck_consent_records_visual_retention_consent"),
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_consent_records_positive_version")),
        sa.CheckConstraint(
            "withdrawn_at IS NULL OR withdrawn_at >= created_at",
            name=op.f("ck_consent_records_withdrawal_time"),
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_profiles.user_id"],
            name=op.f("fk_consent_records_student_id_student_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consent_records")),
        sa.UniqueConstraint("id", "student_id", name=op.f("uq_consent_records_id_student_id")),
        sa.UniqueConstraint(
            "student_id", "version", name=op.f("uq_consent_records_student_id_version")
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_consent_records_student_id"), "consent_records", ["student_id"], unique=False
    )
    op.create_table(
        "conversations",
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "closed",
                name="conversation_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.Column(
            "deleted_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_profiles.user_id"],
            name=op.f("fk_conversations_student_id_student_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint("id", "student_id", name=op.f("uq_conversations_id_student_id")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_conversations_deleted_at"), "conversations", ["deleted_at"], unique=False
    )
    op.create_index(
        "ix_conversations_student_created",
        "conversations",
        ["student_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "reviewer_assignments",
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("reviewer_id", sa.String(length=36), nullable=False),
        sa.Column("assigned_by", sa.String(length=36), nullable=False),
        sa.Column(
            "revoked_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["users.id"],
            name=op.f("fk_reviewer_assignments_assigned_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["reviewer_profiles.user_id"],
            name=op.f("fk_reviewer_assignments_reviewer_id_reviewer_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_profiles.user_id"],
            name=op.f("fk_reviewer_assignments_student_id_student_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviewer_assignments")),
        sa.UniqueConstraint(
            "student_id", "reviewer_id", name=op.f("uq_reviewer_assignments_student_id_reviewer_id")
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_reviewer_assignments_reviewer_id"),
        "reviewer_assignments",
        ["reviewer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reviewer_assignments_student_id"),
        "reviewer_assignments",
        ["student_id"],
        unique=False,
    )
    op.create_table(
        "interaction_sessions",
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column(
            "ended_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.Column(
            "deleted_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True
        ),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at >= created_at",
            name=op.f("ck_interaction_sessions_session_time"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id", "student_id"],
            ["conversations.id", "conversations.student_id"],
            name=op.f("fk_interaction_sessions_conversation_id_conversations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_profiles.user_id"],
            name=op.f("fk_interaction_sessions_student_id_student_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interaction_sessions")),
        sa.UniqueConstraint("id", "student_id", name=op.f("uq_interaction_sessions_id_student_id")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_interaction_sessions_conversation_id"),
        "interaction_sessions",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interaction_sessions_deleted_at"),
        "interaction_sessions",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interaction_sessions_student_id"),
        "interaction_sessions",
        ["student_id"],
        unique=False,
    )
    op.create_table(
        "sentiment_trends",
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("consent_record_id", sa.String(length=36), nullable=False),
        sa.Column("model_version_id", sa.String(length=36), nullable=False),
        sa.Column("dimension", sa.String(length=60), nullable=False),
        sa.Column(
            "window_start",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "window_end", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.Column("algorithm_version", sa.String(length=120), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.Column(
            "deleted_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True
        ),
        sa.CheckConstraint("sample_count > 0", name=op.f("ck_sentiment_trends_trend_sample_count")),
        sa.CheckConstraint(
            "window_end > window_start", name=op.f("ck_sentiment_trends_trend_window")
        ),
        sa.ForeignKeyConstraint(
            ["consent_record_id", "student_id"],
            ["consent_records.id", "consent_records.student_id"],
            name=op.f("fk_sentiment_trends_consent_record_id_consent_records"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_sentiment_trends_model_version_id_model_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_profiles.user_id"],
            name=op.f("fk_sentiment_trends_student_id_student_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sentiment_trends")),
        sa.UniqueConstraint("id", "student_id", name=op.f("uq_sentiment_trends_id_student_id")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_sentiment_trends_deleted_at"), "sentiment_trends", ["deleted_at"], unique=False
    )
    op.create_index(
        "ix_trends_student_window",
        "sentiment_trends",
        ["student_id", "window_start", "window_end"],
        unique=False,
    )
    op.create_table(
        "media_assets",
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("consent_record_id", sa.String(length=36), nullable=False),
        sa.Column(
            "modality",
            sa.Enum(
                "audio", "visual", name="media_modality", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("storage_reference", sa.String(length=255), nullable=False),
        sa.Column(
            "expires_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.Column(
            "purged_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.Column(
            "deleted_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True
        ),
        sa.CheckConstraint("expires_at > created_at", name=op.f("ck_media_assets_media_expiry")),
        sa.ForeignKeyConstraint(
            ["consent_record_id", "student_id"],
            ["consent_records.id", "consent_records.student_id"],
            name=op.f("fk_media_assets_consent_record_id_consent_records"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id", "student_id"],
            ["interaction_sessions.id", "interaction_sessions.student_id"],
            name=op.f("fk_media_assets_session_id_interaction_sessions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_profiles.user_id"],
            name=op.f("fk_media_assets_student_id_student_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
        sa.UniqueConstraint("storage_reference", name=op.f("uq_media_assets_storage_reference")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_media_assets_deleted_at"), "media_assets", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_media_assets_expires_at"), "media_assets", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_media_assets_student_id"), "media_assets", ["student_id"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column(
            "sender",
            sa.Enum(
                "student",
                "assistant",
                "system",
                name="message_sender",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("text_content", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.Column(
            "deleted_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True
        ),
        sa.CheckConstraint("sequence_number >= 0", name=op.f("ck_messages_message_sequence")),
        sa.ForeignKeyConstraint(
            ["session_id", "student_id"],
            ["interaction_sessions.id", "interaction_sessions.student_id"],
            name=op.f("fk_messages_session_id_interaction_sessions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_profiles.user_id"],
            name=op.f("fk_messages_student_id_student_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint(
            "id", "session_id", "student_id", name=op.f("uq_messages_id_session_id_student_id")
        ),
        sa.UniqueConstraint(
            "session_id", "sequence_number", name=op.f("uq_messages_session_id_sequence_number")
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_messages_deleted_at"), "messages", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_messages_student_id"), "messages", ["student_id"], unique=False)
    op.create_table(
        "model_inferences",
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("message_id", sa.String(length=36), nullable=True),
        sa.Column("consent_record_id", sa.String(length=36), nullable=False),
        sa.Column("model_version_id", sa.String(length=36), nullable=False),
        sa.Column(
            "modality",
            sa.Enum(
                "text",
                "audio",
                "visual",
                "multimodal",
                name="inference_modality",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "processing_status",
            sa.Enum(
                "pending",
                "running",
                "completed",
                "failed",
                "cancelled",
                "abstained",
                name="processing_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("preprocessing_version", sa.String(length=120), nullable=False),
        sa.Column("adapter_version", sa.String(length=120), nullable=False),
        sa.Column(
            "started_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True
        ),
        sa.Column(
            "completed_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"),
            nullable=True,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("uncertainty", sa.JSON(), nullable=True),
        sa.Column("uncertainty_method", sa.String(length=120), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.Column(
            "deleted_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR (started_at IS NOT NULL AND completed_at >= started_at)",
            name=op.f("ck_model_inferences_inference_time"),
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_model_inferences_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["consent_record_id", "student_id"],
            ["consent_records.id", "consent_records.student_id"],
            name=op.f("fk_model_inferences_consent_record_id_consent_records"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["message_id", "session_id", "student_id"],
            ["messages.id", "messages.session_id", "messages.student_id"],
            name=op.f("fk_model_inferences_message_id_messages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id", "modality"],
            ["model_versions.id", "model_versions.modality"],
            name=op.f("fk_model_inferences_model_version_id_model_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id", "student_id"],
            ["interaction_sessions.id", "interaction_sessions.student_id"],
            name=op.f("fk_model_inferences_session_id_interaction_sessions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_profiles.user_id"],
            name=op.f("fk_model_inferences_student_id_student_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_inferences")),
        sa.UniqueConstraint("id", "modality", name=op.f("uq_model_inferences_id_modality")),
        sa.UniqueConstraint("id", "student_id", name=op.f("uq_model_inferences_id_student_id")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_inferences_status_created",
        "model_inferences",
        ["processing_status", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_inferences_student_created",
        "model_inferences",
        ["student_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_inferences_consent_record_id"),
        "model_inferences",
        ["consent_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_inferences_deleted_at"), "model_inferences", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_model_inferences_message_id"), "model_inferences", ["message_id"], unique=False
    )
    op.create_index(
        op.f("ix_model_inferences_model_version_id"),
        "model_inferences",
        ["model_version_id"],
        unique=False,
    )
    op.create_table(
        "audio_analyses",
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("inference_id", sa.String(length=36), nullable=False),
        sa.Column("modality", sa.String(length=16), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("limitations", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.CheckConstraint("modality = 'audio'", name=op.f("ck_audio_analyses_analysis_modality")),
        sa.ForeignKeyConstraint(
            ["inference_id", "modality"],
            ["model_inferences.id", "model_inferences.modality"],
            name=op.f("fk_audio_analyses_inference_id_model_inferences"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("inference_id", name=op.f("pk_audio_analyses")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "multimodal_analyses",
        sa.Column("fusion_strategy_version", sa.String(length=120), nullable=False),
        sa.Column("missing_modalities", sa.JSON(), nullable=False),
        sa.Column("inference_id", sa.String(length=36), nullable=False),
        sa.Column("modality", sa.String(length=16), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("limitations", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.CheckConstraint(
            "modality = 'multimodal'", name=op.f("ck_multimodal_analyses_analysis_modality")
        ),
        sa.ForeignKeyConstraint(
            ["inference_id", "modality"],
            ["model_inferences.id", "model_inferences.modality"],
            name=op.f("fk_multimodal_analyses_inference_id_model_inferences"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("inference_id", name=op.f("pk_multimodal_analyses")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "research_dataset_records",
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("inference_id", sa.String(length=36), nullable=False),
        sa.Column("consent_record_id", sa.String(length=36), nullable=False),
        sa.Column("dataset_identifier", sa.String(length=120), nullable=False),
        sa.Column("dataset_version", sa.String(length=80), nullable=False),
        sa.Column("ethics_approval_reference", sa.String(length=120), nullable=False),
        sa.Column("deidentification_version", sa.String(length=120), nullable=False),
        sa.Column(
            "split",
            sa.Enum(
                "train",
                "validation",
                "test",
                name="dataset_split",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "revoked_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.Column(
            "deleted_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["consent_record_id", "student_id"],
            ["consent_records.id", "consent_records.student_id"],
            name=op.f("fk_research_dataset_records_consent_record_id_consent_records"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["inference_id", "student_id"],
            ["model_inferences.id", "model_inferences.student_id"],
            name=op.f("fk_research_dataset_records_inference_id_model_inferences"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_profiles.user_id"],
            name=op.f("fk_research_dataset_records_student_id_student_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_dataset_records")),
        sa.UniqueConstraint(
            "dataset_identifier",
            "dataset_version",
            "inference_id",
            name=op.f(
                "uq_research_dataset_records_dataset_identifier_dataset_version_inference_id"
            ),
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_research_dataset_records_deleted_at"),
        "research_dataset_records",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_dataset_records_student_id"),
        "research_dataset_records",
        ["student_id"],
        unique=False,
    )
    op.create_table(
        "risk_signals",
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("inference_id", sa.String(length=36), nullable=True),
        sa.Column("trend_id", sa.String(length=36), nullable=True),
        sa.Column("signal_code", sa.String(length=80), nullable=False),
        sa.Column(
            "priority",
            sa.Enum(
                "routine",
                "prompt",
                "urgent",
                name="signal_priority",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending_review",
                "acknowledged",
                "resolved",
                "dismissed",
                name="signal_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("explanation", sa.JSON(), nullable=False),
        sa.Column("rule_version", sa.String(length=120), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.Column(
            "deleted_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True
        ),
        sa.CheckConstraint(
            "inference_id IS NOT NULL OR trend_id IS NOT NULL",
            name=op.f("ck_risk_signals_signal_source"),
        ),
        sa.ForeignKeyConstraint(
            ["inference_id", "student_id"],
            ["model_inferences.id", "model_inferences.student_id"],
            name=op.f("fk_risk_signals_inference_id_model_inferences"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_profiles.user_id"],
            name=op.f("fk_risk_signals_student_id_student_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["trend_id", "student_id"],
            ["sentiment_trends.id", "sentiment_trends.student_id"],
            name=op.f("fk_risk_signals_trend_id_sentiment_trends"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_signals")),
        sa.UniqueConstraint("id", "student_id", name=op.f("uq_risk_signals_id_student_id")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_risk_signals_deleted_at"), "risk_signals", ["deleted_at"], unique=False
    )
    op.create_index(
        "ix_risks_student_status", "risk_signals", ["student_id", "status"], unique=False
    )
    op.create_table(
        "sentiment_observations",
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("inference_id", sa.String(length=36), nullable=False),
        sa.Column("dimension", sa.String(length=60), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column(
            "observed_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.Column(
            "deleted_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True
        ),
        sa.CheckConstraint(
            "score >= -1 AND score <= 1", name=op.f("ck_sentiment_observations_sentiment_range")
        ),
        sa.ForeignKeyConstraint(
            ["inference_id", "student_id"],
            ["model_inferences.id", "model_inferences.student_id"],
            name=op.f("fk_sentiment_observations_inference_id_model_inferences"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_profiles.user_id"],
            name=op.f("fk_sentiment_observations_student_id_student_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sentiment_observations")),
        sa.UniqueConstraint(
            "id", "student_id", name=op.f("uq_sentiment_observations_id_student_id")
        ),
        sa.UniqueConstraint(
            "inference_id",
            "dimension",
            name=op.f("uq_sentiment_observations_inference_id_dimension"),
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_observations_student_time",
        "sentiment_observations",
        ["student_id", "observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sentiment_observations_deleted_at"),
        "sentiment_observations",
        ["deleted_at"],
        unique=False,
    )
    op.create_table(
        "text_analyses",
        sa.Column("language", sa.String(length=35), nullable=True),
        sa.Column("inference_id", sa.String(length=36), nullable=False),
        sa.Column("modality", sa.String(length=16), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("limitations", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.CheckConstraint("modality = 'text'", name=op.f("ck_text_analyses_analysis_modality")),
        sa.ForeignKeyConstraint(
            ["inference_id", "modality"],
            ["model_inferences.id", "model_inferences.modality"],
            name=op.f("fk_text_analyses_inference_id_model_inferences"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("inference_id", name=op.f("pk_text_analyses")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "visual_analyses",
        sa.Column("sampled_frame_count", sa.Integer(), nullable=True),
        sa.Column("inference_id", sa.String(length=36), nullable=False),
        sa.Column("modality", sa.String(length=16), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("limitations", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.CheckConstraint(
            "modality = 'visual'", name=op.f("ck_visual_analyses_analysis_modality")
        ),
        sa.ForeignKeyConstraint(
            ["inference_id", "modality"],
            ["model_inferences.id", "model_inferences.modality"],
            name=op.f("fk_visual_analyses_inference_id_model_inferences"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("inference_id", name=op.f("pk_visual_analyses")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "fusion_inputs",
        sa.Column("fusion_inference_id", sa.String(length=36), nullable=False),
        sa.Column("source_inference_id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint(
            "fusion_inference_id <> source_inference_id",
            name=op.f("ck_fusion_inputs_no_self_fusion"),
        ),
        sa.ForeignKeyConstraint(
            ["fusion_inference_id", "student_id"],
            ["model_inferences.id", "model_inferences.student_id"],
            name=op.f("fk_fusion_inputs_fusion_inference_id_model_inferences"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["fusion_inference_id"],
            ["multimodal_analyses.inference_id"],
            name=op.f("fk_fusion_inputs_fusion_inference_id_multimodal_analyses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_inference_id", "student_id"],
            ["model_inferences.id", "model_inferences.student_id"],
            name=op.f("fk_fusion_inputs_source_inference_id_model_inferences"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_profiles.user_id"],
            name=op.f("fk_fusion_inputs_student_id_student_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "fusion_inference_id", "source_inference_id", name=op.f("pk_fusion_inputs")
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "human_reviews",
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("risk_signal_id", sa.String(length=36), nullable=False),
        sa.Column("reviewer_id", sa.String(length=36), nullable=False),
        sa.Column(
            "decision",
            sa.Enum(
                "acknowledge",
                "dismiss",
                "follow_up",
                "refer",
                name="review_decision",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["reviewer_profiles.user_id"],
            name=op.f("fk_human_reviews_reviewer_id_reviewer_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["risk_signal_id", "student_id"],
            ["risk_signals.id", "risk_signals.student_id"],
            name=op.f("fk_human_reviews_risk_signal_id_risk_signals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_profiles.user_id"],
            name=op.f("fk_human_reviews_student_id_student_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_human_reviews")),
        sa.UniqueConstraint("id", "student_id", name=op.f("uq_human_reviews_id_student_id")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_human_reviews_reviewer_id"), "human_reviews", ["reviewer_id"], unique=False
    )
    op.create_index(
        op.f("ix_human_reviews_risk_signal_id"), "human_reviews", ["risk_signal_id"], unique=False
    )
    op.create_table(
        "trend_observations",
        sa.Column("trend_id", sa.String(length=36), nullable=False),
        sa.Column("observation_id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["observation_id", "student_id"],
            ["sentiment_observations.id", "sentiment_observations.student_id"],
            name=op.f("fk_trend_observations_observation_id_sentiment_observations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_profiles.user_id"],
            name=op.f("fk_trend_observations_student_id_student_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["trend_id", "student_id"],
            ["sentiment_trends.id", "sentiment_trends.student_id"],
            name=op.f("fk_trend_observations_trend_id_sentiment_trends"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("trend_id", "observation_id", name=op.f("pk_trend_observations")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "referral_records",
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("human_review_id", sa.String(length=36), nullable=False),
        sa.Column("service_reference", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "offered",
                "accepted",
                "declined",
                "closed",
                name="referral_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "student_decided_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"),
            nullable=True,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False
        ),
        sa.Column(
            "deleted_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["human_review_id", "student_id"],
            ["human_reviews.id", "human_reviews.student_id"],
            name=op.f("fk_referral_records_human_review_id_human_reviews"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_profiles.user_id"],
            name=op.f("fk_referral_records_student_id_student_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_referral_records")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_referral_records_deleted_at"), "referral_records", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_referral_records_human_review_id"),
        "referral_records",
        ["human_review_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_referral_records_student_id"), "referral_records", ["student_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("referral_records")
    op.drop_table("trend_observations")
    op.drop_table("human_reviews")
    op.drop_table("fusion_inputs")
    op.drop_table("visual_analyses")
    op.drop_table("text_analyses")
    op.drop_table("sentiment_observations")
    op.drop_table("risk_signals")
    op.drop_table("research_dataset_records")
    op.drop_table("multimodal_analyses")
    op.drop_table("audio_analyses")
    op.drop_table("model_inferences")
    op.drop_table("messages")
    op.drop_table("media_assets")
    op.drop_table("sentiment_trends")
    op.drop_table("interaction_sessions")
    op.drop_table("reviewer_assignments")
    op.drop_table("conversations")
    op.drop_table("consent_records")
    op.drop_table("user_roles")
    op.drop_table("system_settings")
    op.drop_table("student_profiles")
    op.drop_table("role_permissions")
    op.drop_table("reviewer_profiles")
    op.drop_table("notifications")
    op.drop_table("audit_logs")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("permissions")
    op.drop_table("model_versions")
    # ### end Alembic commands ###
