import { PamatiMascot, PamatiMark } from "@/components/pamati-mascot";
import { ServiceStatus } from "@/components/service-status";
const portals = [
  ["/student", "Student space", "Recent conversations, personal observations, optional check-ins, consent and privacy controls."],
  ["/counselor", "Counselor workspace", "Authorized cases, contextual human review, documented assessments and referrals."],
  ["/admin", "Administration", "Users, role permissions, configuration, retention, audit logs and institutional resources."]
];
export default function Home() {
  return <><header className="dashboard-header"><a className="brand" href="/"><PamatiMark />Pamati<span>AI</span></a><a href="/auth/login">Sign in</a></header><main id="main" className="mx-auto max-w-6xl space-y-8 px-6 py-12"><section className="landing-hero"><PamatiMascot /><div><p className="text-violet-800">Student autonomy. Human oversight.</p><h1 className="mt-4 text-4xl font-semibold">A thoughtful space for student support.</h1><p className="mt-5 text-lg">PamatiAI supports consented sentiment and affect research over time. It does not diagnose conditions or replace professional care.</p><a className="primary-link" href="/student/chat">Start chatting</a><a className="secondary-link" href="/auth/login">Sign in to your account</a></div></section><section aria-label="Role dashboards" className="grid gap-4 md:grid-cols-3">{portals.map(([href, title, description]) => <article key={href} className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-semibold"><a className="text-violet-800 underline" href={href}>{title}</a></h2><p className="mt-3 leading-relaxed">{description}</p></article>)}</section><ServiceStatus /><aside className="rounded-2xl bg-violet-900 p-6 text-white"><h2 className="text-lg font-semibold">Participation stays your choice</h2><p className="mt-2">Text, audio, visual processing, tracking, research use and counselor access have separate consent choices. AI-generated observations and human-reviewed assessments are presented separately.</p></aside></main></>;
}
